package com.Manager.userManager.smcMenu.po;

import java.io.Serializable;
import java.util.Date;

public class SmcMenu implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smc_menu.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smc_menu.upper_id
     *
     * @mbggenerated
     */
    private Long upperId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smc_menu.menu_level
     *
     * @mbggenerated
     */
    private Long menuLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smc_menu.system_code
     *
     * @mbggenerated
     */
    private String systemCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smc_menu.menu_cname
     *
     * @mbggenerated
     */
    private String menuCname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smc_menu.menu_tname
     *
     * @mbggenerated
     */
    private String menuTname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smc_menu.menu_ename
     *
     * @mbggenerated
     */
    private String menuEname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smc_menu.action_url
     *
     * @mbggenerated
     */
    private String actionUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smc_menu.target
     *
     * @mbggenerated
     */
    private String target;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smc_menu.display_no
     *
     * @mbggenerated
     */
    private Long displayNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smc_menu.image
     *
     * @mbggenerated
     */
    private String image;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smc_menu.image_expand
     *
     * @mbggenerated
     */
    private String imageExpand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smc_menu.image_collapse
     *
     * @mbggenerated
     */
    private String imageCollapse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smc_menu.icon_expand
     *
     * @mbggenerated
     */
    private String iconExpand;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smc_menu.icon_collapse
     *
     * @mbggenerated
     */
    private String iconCollapse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smc_menu.task_code
     *
     * @mbggenerated
     */
    private String taskCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smc_menu.route_path
     *
     * @mbggenerated
     */
    private String routePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smc_menu.file_path
     *
     * @mbggenerated
     */
    private String filePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smc_menu.cache_view_name
     *
     * @mbggenerated
     */
    private String cacheViewName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smc_menu.creator_code
     *
     * @mbggenerated
     */
    private String creatorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smc_menu.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smc_menu.updater_code
     *
     * @mbggenerated
     */
    private String updaterCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smc_menu.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smc_menu.valid_ind
     *
     * @mbggenerated
     */
    private String validInd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smc_menu.remark
     *
     * @mbggenerated
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smc_menu.flag
     *
     * @mbggenerated
     */
    private String flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smc_menu.version
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smc_menu.insert_time_for_his
     *
     * @mbggenerated
     */
    private Date insertTimeForHis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smc_menu.operate_time_for_his
     *
     * @mbggenerated
     */
    private Date operateTimeForHis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column smc_menu.style
     *
     * @mbggenerated
     */
    private String style;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table smc_menu
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smc_menu.id
     *
     * @return the value of smc_menu.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smc_menu.id
     *
     * @param id the value for smc_menu.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smc_menu.upper_id
     *
     * @return the value of smc_menu.upper_id
     *
     * @mbggenerated
     */
    public Long getUpperId() {
        return upperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smc_menu.upper_id
     *
     * @param upperId the value for smc_menu.upper_id
     *
     * @mbggenerated
     */
    public void setUpperId(Long upperId) {
        this.upperId = upperId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smc_menu.menu_level
     *
     * @return the value of smc_menu.menu_level
     *
     * @mbggenerated
     */
    public Long getMenuLevel() {
        return menuLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smc_menu.menu_level
     *
     * @param menuLevel the value for smc_menu.menu_level
     *
     * @mbggenerated
     */
    public void setMenuLevel(Long menuLevel) {
        this.menuLevel = menuLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smc_menu.system_code
     *
     * @return the value of smc_menu.system_code
     *
     * @mbggenerated
     */
    public String getSystemCode() {
        return systemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smc_menu.system_code
     *
     * @param systemCode the value for smc_menu.system_code
     *
     * @mbggenerated
     */
    public void setSystemCode(String systemCode) {
        this.systemCode = systemCode == null ? null : systemCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smc_menu.menu_cname
     *
     * @return the value of smc_menu.menu_cname
     *
     * @mbggenerated
     */
    public String getMenuCname() {
        return menuCname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smc_menu.menu_cname
     *
     * @param menuCname the value for smc_menu.menu_cname
     *
     * @mbggenerated
     */
    public void setMenuCname(String menuCname) {
        this.menuCname = menuCname == null ? null : menuCname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smc_menu.menu_tname
     *
     * @return the value of smc_menu.menu_tname
     *
     * @mbggenerated
     */
    public String getMenuTname() {
        return menuTname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smc_menu.menu_tname
     *
     * @param menuTname the value for smc_menu.menu_tname
     *
     * @mbggenerated
     */
    public void setMenuTname(String menuTname) {
        this.menuTname = menuTname == null ? null : menuTname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smc_menu.menu_ename
     *
     * @return the value of smc_menu.menu_ename
     *
     * @mbggenerated
     */
    public String getMenuEname() {
        return menuEname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smc_menu.menu_ename
     *
     * @param menuEname the value for smc_menu.menu_ename
     *
     * @mbggenerated
     */
    public void setMenuEname(String menuEname) {
        this.menuEname = menuEname == null ? null : menuEname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smc_menu.action_url
     *
     * @return the value of smc_menu.action_url
     *
     * @mbggenerated
     */
    public String getActionUrl() {
        return actionUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smc_menu.action_url
     *
     * @param actionUrl the value for smc_menu.action_url
     *
     * @mbggenerated
     */
    public void setActionUrl(String actionUrl) {
        this.actionUrl = actionUrl == null ? null : actionUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smc_menu.target
     *
     * @return the value of smc_menu.target
     *
     * @mbggenerated
     */
    public String getTarget() {
        return target;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smc_menu.target
     *
     * @param target the value for smc_menu.target
     *
     * @mbggenerated
     */
    public void setTarget(String target) {
        this.target = target == null ? null : target.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smc_menu.display_no
     *
     * @return the value of smc_menu.display_no
     *
     * @mbggenerated
     */
    public Long getDisplayNo() {
        return displayNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smc_menu.display_no
     *
     * @param displayNo the value for smc_menu.display_no
     *
     * @mbggenerated
     */
    public void setDisplayNo(Long displayNo) {
        this.displayNo = displayNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smc_menu.image
     *
     * @return the value of smc_menu.image
     *
     * @mbggenerated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smc_menu.image
     *
     * @param image the value for smc_menu.image
     *
     * @mbggenerated
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smc_menu.image_expand
     *
     * @return the value of smc_menu.image_expand
     *
     * @mbggenerated
     */
    public String getImageExpand() {
        return imageExpand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smc_menu.image_expand
     *
     * @param imageExpand the value for smc_menu.image_expand
     *
     * @mbggenerated
     */
    public void setImageExpand(String imageExpand) {
        this.imageExpand = imageExpand == null ? null : imageExpand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smc_menu.image_collapse
     *
     * @return the value of smc_menu.image_collapse
     *
     * @mbggenerated
     */
    public String getImageCollapse() {
        return imageCollapse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smc_menu.image_collapse
     *
     * @param imageCollapse the value for smc_menu.image_collapse
     *
     * @mbggenerated
     */
    public void setImageCollapse(String imageCollapse) {
        this.imageCollapse = imageCollapse == null ? null : imageCollapse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smc_menu.icon_expand
     *
     * @return the value of smc_menu.icon_expand
     *
     * @mbggenerated
     */
    public String getIconExpand() {
        return iconExpand;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smc_menu.icon_expand
     *
     * @param iconExpand the value for smc_menu.icon_expand
     *
     * @mbggenerated
     */
    public void setIconExpand(String iconExpand) {
        this.iconExpand = iconExpand == null ? null : iconExpand.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smc_menu.icon_collapse
     *
     * @return the value of smc_menu.icon_collapse
     *
     * @mbggenerated
     */
    public String getIconCollapse() {
        return iconCollapse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smc_menu.icon_collapse
     *
     * @param iconCollapse the value for smc_menu.icon_collapse
     *
     * @mbggenerated
     */
    public void setIconCollapse(String iconCollapse) {
        this.iconCollapse = iconCollapse == null ? null : iconCollapse.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smc_menu.task_code
     *
     * @return the value of smc_menu.task_code
     *
     * @mbggenerated
     */
    public String getTaskCode() {
        return taskCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smc_menu.task_code
     *
     * @param taskCode the value for smc_menu.task_code
     *
     * @mbggenerated
     */
    public void setTaskCode(String taskCode) {
        this.taskCode = taskCode == null ? null : taskCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smc_menu.route_path
     *
     * @return the value of smc_menu.route_path
     *
     * @mbggenerated
     */
    public String getRoutePath() {
        return routePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smc_menu.route_path
     *
     * @param routePath the value for smc_menu.route_path
     *
     * @mbggenerated
     */
    public void setRoutePath(String routePath) {
        this.routePath = routePath == null ? null : routePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smc_menu.file_path
     *
     * @return the value of smc_menu.file_path
     *
     * @mbggenerated
     */
    public String getFilePath() {
        return filePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smc_menu.file_path
     *
     * @param filePath the value for smc_menu.file_path
     *
     * @mbggenerated
     */
    public void setFilePath(String filePath) {
        this.filePath = filePath == null ? null : filePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smc_menu.cache_view_name
     *
     * @return the value of smc_menu.cache_view_name
     *
     * @mbggenerated
     */
    public String getCacheViewName() {
        return cacheViewName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smc_menu.cache_view_name
     *
     * @param cacheViewName the value for smc_menu.cache_view_name
     *
     * @mbggenerated
     */
    public void setCacheViewName(String cacheViewName) {
        this.cacheViewName = cacheViewName == null ? null : cacheViewName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smc_menu.creator_code
     *
     * @return the value of smc_menu.creator_code
     *
     * @mbggenerated
     */
    public String getCreatorCode() {
        return creatorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smc_menu.creator_code
     *
     * @param creatorCode the value for smc_menu.creator_code
     *
     * @mbggenerated
     */
    public void setCreatorCode(String creatorCode) {
        this.creatorCode = creatorCode == null ? null : creatorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smc_menu.create_time
     *
     * @return the value of smc_menu.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smc_menu.create_time
     *
     * @param createTime the value for smc_menu.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smc_menu.updater_code
     *
     * @return the value of smc_menu.updater_code
     *
     * @mbggenerated
     */
    public String getUpdaterCode() {
        return updaterCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smc_menu.updater_code
     *
     * @param updaterCode the value for smc_menu.updater_code
     *
     * @mbggenerated
     */
    public void setUpdaterCode(String updaterCode) {
        this.updaterCode = updaterCode == null ? null : updaterCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smc_menu.update_time
     *
     * @return the value of smc_menu.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smc_menu.update_time
     *
     * @param updateTime the value for smc_menu.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smc_menu.valid_ind
     *
     * @return the value of smc_menu.valid_ind
     *
     * @mbggenerated
     */
    public String getValidInd() {
        return validInd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smc_menu.valid_ind
     *
     * @param validInd the value for smc_menu.valid_ind
     *
     * @mbggenerated
     */
    public void setValidInd(String validInd) {
        this.validInd = validInd == null ? null : validInd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smc_menu.remark
     *
     * @return the value of smc_menu.remark
     *
     * @mbggenerated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smc_menu.remark
     *
     * @param remark the value for smc_menu.remark
     *
     * @mbggenerated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smc_menu.flag
     *
     * @return the value of smc_menu.flag
     *
     * @mbggenerated
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smc_menu.flag
     *
     * @param flag the value for smc_menu.flag
     *
     * @mbggenerated
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smc_menu.version
     *
     * @return the value of smc_menu.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smc_menu.version
     *
     * @param version the value for smc_menu.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smc_menu.insert_time_for_his
     *
     * @return the value of smc_menu.insert_time_for_his
     *
     * @mbggenerated
     */
    public Date getInsertTimeForHis() {
        return insertTimeForHis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smc_menu.insert_time_for_his
     *
     * @param insertTimeForHis the value for smc_menu.insert_time_for_his
     *
     * @mbggenerated
     */
    public void setInsertTimeForHis(Date insertTimeForHis) {
        this.insertTimeForHis = insertTimeForHis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smc_menu.operate_time_for_his
     *
     * @return the value of smc_menu.operate_time_for_his
     *
     * @mbggenerated
     */
    public Date getOperateTimeForHis() {
        return operateTimeForHis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smc_menu.operate_time_for_his
     *
     * @param operateTimeForHis the value for smc_menu.operate_time_for_his
     *
     * @mbggenerated
     */
    public void setOperateTimeForHis(Date operateTimeForHis) {
        this.operateTimeForHis = operateTimeForHis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column smc_menu.style
     *
     * @return the value of smc_menu.style
     *
     * @mbggenerated
     */
    public String getStyle() {
        return style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column smc_menu.style
     *
     * @param style the value for smc_menu.style
     *
     * @mbggenerated
     */
    public void setStyle(String style) {
        this.style = style == null ? null : style.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smc_menu
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", upperId=").append(upperId);
        sb.append(", menuLevel=").append(menuLevel);
        sb.append(", systemCode=").append(systemCode);
        sb.append(", menuCname=").append(menuCname);
        sb.append(", menuTname=").append(menuTname);
        sb.append(", menuEname=").append(menuEname);
        sb.append(", actionUrl=").append(actionUrl);
        sb.append(", target=").append(target);
        sb.append(", displayNo=").append(displayNo);
        sb.append(", image=").append(image);
        sb.append(", imageExpand=").append(imageExpand);
        sb.append(", imageCollapse=").append(imageCollapse);
        sb.append(", iconExpand=").append(iconExpand);
        sb.append(", iconCollapse=").append(iconCollapse);
        sb.append(", taskCode=").append(taskCode);
        sb.append(", routePath=").append(routePath);
        sb.append(", filePath=").append(filePath);
        sb.append(", cacheViewName=").append(cacheViewName);
        sb.append(", creatorCode=").append(creatorCode);
        sb.append(", createTime=").append(createTime);
        sb.append(", updaterCode=").append(updaterCode);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", validInd=").append(validInd);
        sb.append(", remark=").append(remark);
        sb.append(", flag=").append(flag);
        sb.append(", version=").append(version);
        sb.append(", insertTimeForHis=").append(insertTimeForHis);
        sb.append(", operateTimeForHis=").append(operateTimeForHis);
        sb.append(", style=").append(style);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}