package com.Manager.userManager.saaUserRole.dao;

import com.Manager.userManager.saaUserRole.po.SaaUserRole;
import java.util.List;

public interface SaaUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saa_user_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saa_user_role
     *
     * @mbggenerated
     */
    int insert(SaaUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saa_user_role
     *
     * @mbggenerated
     */
    SaaUserRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saa_user_role
     *
     * @mbggenerated
     */
    List<SaaUserRole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saa_user_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SaaUserRole record);
}