server:
  port: 8081
  servlet:
    context-parameters:
      enable: true
      maxShowParam: 1
      minTime: -1
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/manager?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: admin
mybatis:
  executor-type: REUSE
  mapperLocations: classpath*:mappers/*Mapper.xml
#showSql
logging:
  level:
    com:
      Manager:
        mapper : debug