package com.Manager.userManager.saaRole.dao;

import com.Manager.userManager.saaRole.po.SaaRole;
import java.util.List;

public interface SaaRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saa_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String roleCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saa_role
     *
     * @mbggenerated
     */
    int insert(SaaRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saa_role
     *
     * @mbggenerated
     */
    SaaRole selectByPrimaryKey(String roleCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saa_role
     *
     * @mbggenerated
     */
    List<SaaRole> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saa_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SaaRole record);
}