package com.Manager.userManager.sysApplication.dao;

import com.Manager.userManager.sysApplication.po.SysApplication;
import java.util.List;

public interface SysApplicationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_application
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_application
     *
     * @mbggenerated
     */
    int insert(SysApplication record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_application
     *
     * @mbggenerated
     */
    SysApplication selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_application
     *
     * @mbggenerated
     */
    List<SysApplication> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_application
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysApplication record);
}