package com.Manager.userManager.saaFactor.dao;

import com.Manager.userManager.saaFactor.po.SaaFactor;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Repository;

import java.util.List;
@Repository
@Mapper
public interface SaaFactorMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saa_factor
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String factorCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saa_factor
     *
     * @mbggenerated
     */
    int insert(SaaFactor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saa_factor
     *
     * @mbggenerated
     */
    SaaFactor selectByPrimaryKey(String factorCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saa_factor
     *
     * @mbggenerated
     */
    List<SaaFactor> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saa_factor
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SaaFactor record);
}