package com.Manager.userManager.smcMenu.dao;

import com.Manager.userManager.smcMenu.po.SmcMenu;
import java.util.List;

public interface SmcMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smc_menu
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smc_menu
     *
     * @mbggenerated
     */
    int insert(SmcMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smc_menu
     *
     * @mbggenerated
     */
    SmcMenu selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smc_menu
     *
     * @mbggenerated
     */
    List<SmcMenu> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table smc_menu
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SmcMenu record);
}