package com.Manager.userManager.saaRolePower.dao;

import com.Manager.userManager.saaRolePower.po.SaaRolePower;
import java.util.List;

public interface SaaRolePowerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saa_role_power
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saa_role_power
     *
     * @mbggenerated
     */
    int insert(SaaRolePower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saa_role_power
     *
     * @mbggenerated
     */
    SaaRolePower selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saa_role_power
     *
     * @mbggenerated
     */
    List<SaaRolePower> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saa_role_power
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SaaRolePower record);
}