package com.Manager.userManager.sysUserProperty.dao;

import com.Manager.userManager.sysUserProperty.po.SysUserProperty;
import java.util.List;

public interface SysUserPropertyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_property
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_property
     *
     * @mbggenerated
     */
    int insert(SysUserProperty record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_property
     *
     * @mbggenerated
     */
    SysUserProperty selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_property
     *
     * @mbggenerated
     */
    List<SysUserProperty> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_user_property
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysUserProperty record);
}