package com.Manager.userManager.sddType.dao;

import com.Manager.userManager.sddType.po.SddType;
import java.util.List;

public interface SddTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdd_type
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdd_type
     *
     * @mbggenerated
     */
    int insert(SddType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdd_type
     *
     * @mbggenerated
     */
    SddType selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdd_type
     *
     * @mbggenerated
     */
    List<SddType> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdd_type
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SddType record);
}