package com.Manager.userManager.sysCompany.dao;

import com.Manager.userManager.sysCompany.po.SysCompany;
import java.util.List;

public interface SysCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String comCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbggenerated
     */
    int insert(SysCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbggenerated
     */
    SysCompany selectByPrimaryKey(String comCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbggenerated
     */
    List<SysCompany> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_company
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SysCompany record);
}