package com.Manager.userManager.smsTemplate.po;

import java.io.Serializable;
import java.util.Date;

public class SmsTemplate implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_template.template_code
     *
     * @mbggenerated
     */
    private String templateCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_template.theme
     *
     * @mbggenerated
     */
    private String theme;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_template.sys_code
     *
     * @mbggenerated
     */
    private String sysCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_template.com_code
     *
     * @mbggenerated
     */
    private String comCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_template.template_content
     *
     * @mbggenerated
     */
    private String templateContent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_template.version
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_template.insert_time_for_his
     *
     * @mbggenerated
     */
    private Date insertTimeForHis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_template.operate_time_for_his
     *
     * @mbggenerated
     */
    private Date operateTimeForHis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_template.valid_status
     *
     * @mbggenerated
     */
    private String validStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sms_template
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_template.template_code
     *
     * @return the value of sms_template.template_code
     *
     * @mbggenerated
     */
    public String getTemplateCode() {
        return templateCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_template.template_code
     *
     * @param templateCode the value for sms_template.template_code
     *
     * @mbggenerated
     */
    public void setTemplateCode(String templateCode) {
        this.templateCode = templateCode == null ? null : templateCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_template.theme
     *
     * @return the value of sms_template.theme
     *
     * @mbggenerated
     */
    public String getTheme() {
        return theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_template.theme
     *
     * @param theme the value for sms_template.theme
     *
     * @mbggenerated
     */
    public void setTheme(String theme) {
        this.theme = theme == null ? null : theme.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_template.sys_code
     *
     * @return the value of sms_template.sys_code
     *
     * @mbggenerated
     */
    public String getSysCode() {
        return sysCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_template.sys_code
     *
     * @param sysCode the value for sms_template.sys_code
     *
     * @mbggenerated
     */
    public void setSysCode(String sysCode) {
        this.sysCode = sysCode == null ? null : sysCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_template.com_code
     *
     * @return the value of sms_template.com_code
     *
     * @mbggenerated
     */
    public String getComCode() {
        return comCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_template.com_code
     *
     * @param comCode the value for sms_template.com_code
     *
     * @mbggenerated
     */
    public void setComCode(String comCode) {
        this.comCode = comCode == null ? null : comCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_template.template_content
     *
     * @return the value of sms_template.template_content
     *
     * @mbggenerated
     */
    public String getTemplateContent() {
        return templateContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_template.template_content
     *
     * @param templateContent the value for sms_template.template_content
     *
     * @mbggenerated
     */
    public void setTemplateContent(String templateContent) {
        this.templateContent = templateContent == null ? null : templateContent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_template.version
     *
     * @return the value of sms_template.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_template.version
     *
     * @param version the value for sms_template.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_template.insert_time_for_his
     *
     * @return the value of sms_template.insert_time_for_his
     *
     * @mbggenerated
     */
    public Date getInsertTimeForHis() {
        return insertTimeForHis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_template.insert_time_for_his
     *
     * @param insertTimeForHis the value for sms_template.insert_time_for_his
     *
     * @mbggenerated
     */
    public void setInsertTimeForHis(Date insertTimeForHis) {
        this.insertTimeForHis = insertTimeForHis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_template.operate_time_for_his
     *
     * @return the value of sms_template.operate_time_for_his
     *
     * @mbggenerated
     */
    public Date getOperateTimeForHis() {
        return operateTimeForHis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_template.operate_time_for_his
     *
     * @param operateTimeForHis the value for sms_template.operate_time_for_his
     *
     * @mbggenerated
     */
    public void setOperateTimeForHis(Date operateTimeForHis) {
        this.operateTimeForHis = operateTimeForHis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_template.valid_status
     *
     * @return the value of sms_template.valid_status
     *
     * @mbggenerated
     */
    public String getValidStatus() {
        return validStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_template.valid_status
     *
     * @param validStatus the value for sms_template.valid_status
     *
     * @mbggenerated
     */
    public void setValidStatus(String validStatus) {
        this.validStatus = validStatus == null ? null : validStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_template
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", templateCode=").append(templateCode);
        sb.append(", theme=").append(theme);
        sb.append(", sysCode=").append(sysCode);
        sb.append(", comCode=").append(comCode);
        sb.append(", templateContent=").append(templateContent);
        sb.append(", version=").append(version);
        sb.append(", insertTimeForHis=").append(insertTimeForHis);
        sb.append(", operateTimeForHis=").append(operateTimeForHis);
        sb.append(", validStatus=").append(validStatus);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}