package com.Manager.userManager.sddCode.dao;

import com.Manager.userManager.sddCode.po.SddCode;
import java.util.List;

public interface SddCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdd_code
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdd_code
     *
     * @mbggenerated
     */
    int insert(SddCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdd_code
     *
     * @mbggenerated
     */
    SddCode selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdd_code
     *
     * @mbggenerated
     */
    List<SddCode> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdd_code
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SddCode record);
}