package com.Manager.userManager.saaRolePower.po;

import java.io.Serializable;
import java.util.Date;

public class SaaRolePower implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saa_role_power.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saa_role_power.role_code
     *
     * @mbggenerated
     */
    private String roleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saa_role_power.factor_code
     *
     * @mbggenerated
     */
    private String factorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saa_role_power.data_oper
     *
     * @mbggenerated
     */
    private String dataOper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saa_role_power.data_value
     *
     * @mbggenerated
     */
    private String dataValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saa_role_power.system_code
     *
     * @mbggenerated
     */
    private String systemCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saa_role_power.version
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saa_role_power.insert_time_for_his
     *
     * @mbggenerated
     */
    private Date insertTimeForHis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saa_role_power.operate_time_for_his
     *
     * @mbggenerated
     */
    private Date operateTimeForHis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table saa_role_power
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saa_role_power.id
     *
     * @return the value of saa_role_power.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saa_role_power.id
     *
     * @param id the value for saa_role_power.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saa_role_power.role_code
     *
     * @return the value of saa_role_power.role_code
     *
     * @mbggenerated
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saa_role_power.role_code
     *
     * @param roleCode the value for saa_role_power.role_code
     *
     * @mbggenerated
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saa_role_power.factor_code
     *
     * @return the value of saa_role_power.factor_code
     *
     * @mbggenerated
     */
    public String getFactorCode() {
        return factorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saa_role_power.factor_code
     *
     * @param factorCode the value for saa_role_power.factor_code
     *
     * @mbggenerated
     */
    public void setFactorCode(String factorCode) {
        this.factorCode = factorCode == null ? null : factorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saa_role_power.data_oper
     *
     * @return the value of saa_role_power.data_oper
     *
     * @mbggenerated
     */
    public String getDataOper() {
        return dataOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saa_role_power.data_oper
     *
     * @param dataOper the value for saa_role_power.data_oper
     *
     * @mbggenerated
     */
    public void setDataOper(String dataOper) {
        this.dataOper = dataOper == null ? null : dataOper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saa_role_power.data_value
     *
     * @return the value of saa_role_power.data_value
     *
     * @mbggenerated
     */
    public String getDataValue() {
        return dataValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saa_role_power.data_value
     *
     * @param dataValue the value for saa_role_power.data_value
     *
     * @mbggenerated
     */
    public void setDataValue(String dataValue) {
        this.dataValue = dataValue == null ? null : dataValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saa_role_power.system_code
     *
     * @return the value of saa_role_power.system_code
     *
     * @mbggenerated
     */
    public String getSystemCode() {
        return systemCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saa_role_power.system_code
     *
     * @param systemCode the value for saa_role_power.system_code
     *
     * @mbggenerated
     */
    public void setSystemCode(String systemCode) {
        this.systemCode = systemCode == null ? null : systemCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saa_role_power.version
     *
     * @return the value of saa_role_power.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saa_role_power.version
     *
     * @param version the value for saa_role_power.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saa_role_power.insert_time_for_his
     *
     * @return the value of saa_role_power.insert_time_for_his
     *
     * @mbggenerated
     */
    public Date getInsertTimeForHis() {
        return insertTimeForHis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saa_role_power.insert_time_for_his
     *
     * @param insertTimeForHis the value for saa_role_power.insert_time_for_his
     *
     * @mbggenerated
     */
    public void setInsertTimeForHis(Date insertTimeForHis) {
        this.insertTimeForHis = insertTimeForHis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saa_role_power.operate_time_for_his
     *
     * @return the value of saa_role_power.operate_time_for_his
     *
     * @mbggenerated
     */
    public Date getOperateTimeForHis() {
        return operateTimeForHis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saa_role_power.operate_time_for_his
     *
     * @param operateTimeForHis the value for saa_role_power.operate_time_for_his
     *
     * @mbggenerated
     */
    public void setOperateTimeForHis(Date operateTimeForHis) {
        this.operateTimeForHis = operateTimeForHis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saa_role_power
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", roleCode=").append(roleCode);
        sb.append(", factorCode=").append(factorCode);
        sb.append(", dataOper=").append(dataOper);
        sb.append(", dataValue=").append(dataValue);
        sb.append(", systemCode=").append(systemCode);
        sb.append(", version=").append(version);
        sb.append(", insertTimeForHis=").append(insertTimeForHis);
        sb.append(", operateTimeForHis=").append(operateTimeForHis);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}