package com.Manager.userManager.saaFactorField.po;

import java.io.Serializable;
import java.util.Date;

public class SaaFactorField implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saa_factor_field.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saa_factor_field.factor_code
     *
     * @mbggenerated
     */
    private String factorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saa_factor_field.field_code
     *
     * @mbggenerated
     */
    private String fieldCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saa_factor_field.entity_code
     *
     * @mbggenerated
     */
    private String entityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saa_factor_field.version
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saa_factor_field.insert_time_for_his
     *
     * @mbggenerated
     */
    private Date insertTimeForHis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saa_factor_field.operate_time_for_his
     *
     * @mbggenerated
     */
    private Date operateTimeForHis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table saa_factor_field
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saa_factor_field.id
     *
     * @return the value of saa_factor_field.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saa_factor_field.id
     *
     * @param id the value for saa_factor_field.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saa_factor_field.factor_code
     *
     * @return the value of saa_factor_field.factor_code
     *
     * @mbggenerated
     */
    public String getFactorCode() {
        return factorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saa_factor_field.factor_code
     *
     * @param factorCode the value for saa_factor_field.factor_code
     *
     * @mbggenerated
     */
    public void setFactorCode(String factorCode) {
        this.factorCode = factorCode == null ? null : factorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saa_factor_field.field_code
     *
     * @return the value of saa_factor_field.field_code
     *
     * @mbggenerated
     */
    public String getFieldCode() {
        return fieldCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saa_factor_field.field_code
     *
     * @param fieldCode the value for saa_factor_field.field_code
     *
     * @mbggenerated
     */
    public void setFieldCode(String fieldCode) {
        this.fieldCode = fieldCode == null ? null : fieldCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saa_factor_field.entity_code
     *
     * @return the value of saa_factor_field.entity_code
     *
     * @mbggenerated
     */
    public String getEntityCode() {
        return entityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saa_factor_field.entity_code
     *
     * @param entityCode the value for saa_factor_field.entity_code
     *
     * @mbggenerated
     */
    public void setEntityCode(String entityCode) {
        this.entityCode = entityCode == null ? null : entityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saa_factor_field.version
     *
     * @return the value of saa_factor_field.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saa_factor_field.version
     *
     * @param version the value for saa_factor_field.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saa_factor_field.insert_time_for_his
     *
     * @return the value of saa_factor_field.insert_time_for_his
     *
     * @mbggenerated
     */
    public Date getInsertTimeForHis() {
        return insertTimeForHis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saa_factor_field.insert_time_for_his
     *
     * @param insertTimeForHis the value for saa_factor_field.insert_time_for_his
     *
     * @mbggenerated
     */
    public void setInsertTimeForHis(Date insertTimeForHis) {
        this.insertTimeForHis = insertTimeForHis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saa_factor_field.operate_time_for_his
     *
     * @return the value of saa_factor_field.operate_time_for_his
     *
     * @mbggenerated
     */
    public Date getOperateTimeForHis() {
        return operateTimeForHis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saa_factor_field.operate_time_for_his
     *
     * @param operateTimeForHis the value for saa_factor_field.operate_time_for_his
     *
     * @mbggenerated
     */
    public void setOperateTimeForHis(Date operateTimeForHis) {
        this.operateTimeForHis = operateTimeForHis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saa_factor_field
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", factorCode=").append(factorCode);
        sb.append(", fieldCode=").append(fieldCode);
        sb.append(", entityCode=").append(entityCode);
        sb.append(", version=").append(version);
        sb.append(", insertTimeForHis=").append(insertTimeForHis);
        sb.append(", operateTimeForHis=").append(operateTimeForHis);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}