package com.Manager.userManager.sddCode.po;

import java.io.Serializable;
import java.util.Date;

public class SddCode implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdd_code.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdd_code.type_id
     *
     * @mbggenerated
     */
    private Long typeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdd_code.code
     *
     * @mbggenerated
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdd_code.value
     *
     * @mbggenerated
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdd_code.language
     *
     * @mbggenerated
     */
    private String language;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdd_code.display_no
     *
     * @mbggenerated
     */
    private Float displayNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdd_code.code_desc
     *
     * @mbggenerated
     */
    private String codeDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdd_code.valid_status
     *
     * @mbggenerated
     */
    private String validStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdd_code.flag
     *
     * @mbggenerated
     */
    private String flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdd_code.version
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdd_code.insert_time_for_his
     *
     * @mbggenerated
     */
    private Date insertTimeForHis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sdd_code.operate_time_for_his
     *
     * @mbggenerated
     */
    private Date operateTimeForHis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sdd_code
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdd_code.id
     *
     * @return the value of sdd_code.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdd_code.id
     *
     * @param id the value for sdd_code.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdd_code.type_id
     *
     * @return the value of sdd_code.type_id
     *
     * @mbggenerated
     */
    public Long getTypeId() {
        return typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdd_code.type_id
     *
     * @param typeId the value for sdd_code.type_id
     *
     * @mbggenerated
     */
    public void setTypeId(Long typeId) {
        this.typeId = typeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdd_code.code
     *
     * @return the value of sdd_code.code
     *
     * @mbggenerated
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdd_code.code
     *
     * @param code the value for sdd_code.code
     *
     * @mbggenerated
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdd_code.value
     *
     * @return the value of sdd_code.value
     *
     * @mbggenerated
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdd_code.value
     *
     * @param value the value for sdd_code.value
     *
     * @mbggenerated
     */
    public void setValue(String value) {
        this.value = value == null ? null : value.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdd_code.language
     *
     * @return the value of sdd_code.language
     *
     * @mbggenerated
     */
    public String getLanguage() {
        return language;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdd_code.language
     *
     * @param language the value for sdd_code.language
     *
     * @mbggenerated
     */
    public void setLanguage(String language) {
        this.language = language == null ? null : language.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdd_code.display_no
     *
     * @return the value of sdd_code.display_no
     *
     * @mbggenerated
     */
    public Float getDisplayNo() {
        return displayNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdd_code.display_no
     *
     * @param displayNo the value for sdd_code.display_no
     *
     * @mbggenerated
     */
    public void setDisplayNo(Float displayNo) {
        this.displayNo = displayNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdd_code.code_desc
     *
     * @return the value of sdd_code.code_desc
     *
     * @mbggenerated
     */
    public String getCodeDesc() {
        return codeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdd_code.code_desc
     *
     * @param codeDesc the value for sdd_code.code_desc
     *
     * @mbggenerated
     */
    public void setCodeDesc(String codeDesc) {
        this.codeDesc = codeDesc == null ? null : codeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdd_code.valid_status
     *
     * @return the value of sdd_code.valid_status
     *
     * @mbggenerated
     */
    public String getValidStatus() {
        return validStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdd_code.valid_status
     *
     * @param validStatus the value for sdd_code.valid_status
     *
     * @mbggenerated
     */
    public void setValidStatus(String validStatus) {
        this.validStatus = validStatus == null ? null : validStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdd_code.flag
     *
     * @return the value of sdd_code.flag
     *
     * @mbggenerated
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdd_code.flag
     *
     * @param flag the value for sdd_code.flag
     *
     * @mbggenerated
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdd_code.version
     *
     * @return the value of sdd_code.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdd_code.version
     *
     * @param version the value for sdd_code.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdd_code.insert_time_for_his
     *
     * @return the value of sdd_code.insert_time_for_his
     *
     * @mbggenerated
     */
    public Date getInsertTimeForHis() {
        return insertTimeForHis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdd_code.insert_time_for_his
     *
     * @param insertTimeForHis the value for sdd_code.insert_time_for_his
     *
     * @mbggenerated
     */
    public void setInsertTimeForHis(Date insertTimeForHis) {
        this.insertTimeForHis = insertTimeForHis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sdd_code.operate_time_for_his
     *
     * @return the value of sdd_code.operate_time_for_his
     *
     * @mbggenerated
     */
    public Date getOperateTimeForHis() {
        return operateTimeForHis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sdd_code.operate_time_for_his
     *
     * @param operateTimeForHis the value for sdd_code.operate_time_for_his
     *
     * @mbggenerated
     */
    public void setOperateTimeForHis(Date operateTimeForHis) {
        this.operateTimeForHis = operateTimeForHis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sdd_code
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", typeId=").append(typeId);
        sb.append(", code=").append(code);
        sb.append(", value=").append(value);
        sb.append(", language=").append(language);
        sb.append(", displayNo=").append(displayNo);
        sb.append(", codeDesc=").append(codeDesc);
        sb.append(", validStatus=").append(validStatus);
        sb.append(", flag=").append(flag);
        sb.append(", version=").append(version);
        sb.append(", insertTimeForHis=").append(insertTimeForHis);
        sb.append(", operateTimeForHis=").append(operateTimeForHis);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}