package com.Manager.userManager.smsTemplate.dao;

import com.Manager.userManager.smsTemplate.po.SmsTemplate;
import java.util.List;

public interface SmsTemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_template
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String templateCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_template
     *
     * @mbggenerated
     */
    int insert(SmsTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_template
     *
     * @mbggenerated
     */
    SmsTemplate selectByPrimaryKey(String templateCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_template
     *
     * @mbggenerated
     */
    List<SmsTemplate> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_template
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SmsTemplate record);
}