package com.Manager.userManager.saaUserRole.po;

import java.io.Serializable;
import java.util.Date;

public class SaaUserRole implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saa_user_role.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saa_user_role.user_code
     *
     * @mbggenerated
     */
    private String userCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saa_user_role.role_code
     *
     * @mbggenerated
     */
    private String roleCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saa_user_role.start_date
     *
     * @mbggenerated
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saa_user_role.end_date
     *
     * @mbggenerated
     */
    private Date endDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saa_user_role.updater_code
     *
     * @mbggenerated
     */
    private String updaterCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saa_user_role.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saa_user_role.version
     *
     * @mbggenerated
     */
    private Integer version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saa_user_role.insert_time_for_his
     *
     * @mbggenerated
     */
    private Date insertTimeForHis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column saa_user_role.operate_time_for_his
     *
     * @mbggenerated
     */
    private Date operateTimeForHis;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table saa_user_role
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saa_user_role.id
     *
     * @return the value of saa_user_role.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saa_user_role.id
     *
     * @param id the value for saa_user_role.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saa_user_role.user_code
     *
     * @return the value of saa_user_role.user_code
     *
     * @mbggenerated
     */
    public String getUserCode() {
        return userCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saa_user_role.user_code
     *
     * @param userCode the value for saa_user_role.user_code
     *
     * @mbggenerated
     */
    public void setUserCode(String userCode) {
        this.userCode = userCode == null ? null : userCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saa_user_role.role_code
     *
     * @return the value of saa_user_role.role_code
     *
     * @mbggenerated
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saa_user_role.role_code
     *
     * @param roleCode the value for saa_user_role.role_code
     *
     * @mbggenerated
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saa_user_role.start_date
     *
     * @return the value of saa_user_role.start_date
     *
     * @mbggenerated
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saa_user_role.start_date
     *
     * @param startDate the value for saa_user_role.start_date
     *
     * @mbggenerated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saa_user_role.end_date
     *
     * @return the value of saa_user_role.end_date
     *
     * @mbggenerated
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saa_user_role.end_date
     *
     * @param endDate the value for saa_user_role.end_date
     *
     * @mbggenerated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saa_user_role.updater_code
     *
     * @return the value of saa_user_role.updater_code
     *
     * @mbggenerated
     */
    public String getUpdaterCode() {
        return updaterCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saa_user_role.updater_code
     *
     * @param updaterCode the value for saa_user_role.updater_code
     *
     * @mbggenerated
     */
    public void setUpdaterCode(String updaterCode) {
        this.updaterCode = updaterCode == null ? null : updaterCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saa_user_role.update_time
     *
     * @return the value of saa_user_role.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saa_user_role.update_time
     *
     * @param updateTime the value for saa_user_role.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saa_user_role.version
     *
     * @return the value of saa_user_role.version
     *
     * @mbggenerated
     */
    public Integer getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saa_user_role.version
     *
     * @param version the value for saa_user_role.version
     *
     * @mbggenerated
     */
    public void setVersion(Integer version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saa_user_role.insert_time_for_his
     *
     * @return the value of saa_user_role.insert_time_for_his
     *
     * @mbggenerated
     */
    public Date getInsertTimeForHis() {
        return insertTimeForHis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saa_user_role.insert_time_for_his
     *
     * @param insertTimeForHis the value for saa_user_role.insert_time_for_his
     *
     * @mbggenerated
     */
    public void setInsertTimeForHis(Date insertTimeForHis) {
        this.insertTimeForHis = insertTimeForHis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column saa_user_role.operate_time_for_his
     *
     * @return the value of saa_user_role.operate_time_for_his
     *
     * @mbggenerated
     */
    public Date getOperateTimeForHis() {
        return operateTimeForHis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column saa_user_role.operate_time_for_his
     *
     * @param operateTimeForHis the value for saa_user_role.operate_time_for_his
     *
     * @mbggenerated
     */
    public void setOperateTimeForHis(Date operateTimeForHis) {
        this.operateTimeForHis = operateTimeForHis;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saa_user_role
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userCode=").append(userCode);
        sb.append(", roleCode=").append(roleCode);
        sb.append(", startDate=").append(startDate);
        sb.append(", endDate=").append(endDate);
        sb.append(", updaterCode=").append(updaterCode);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", version=").append(version);
        sb.append(", insertTimeForHis=").append(insertTimeForHis);
        sb.append(", operateTimeForHis=").append(operateTimeForHis);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}