package com.Manager.userManager.saaRoleTask.dao;

import com.Manager.userManager.saaRoleTask.po.SaaRoleTask;
import java.util.List;

public interface SaaRoleTaskMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saa_role_task
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saa_role_task
     *
     * @mbggenerated
     */
    int insert(SaaRoleTask record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saa_role_task
     *
     * @mbggenerated
     */
    SaaRoleTask selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saa_role_task
     *
     * @mbggenerated
     */
    List<SaaRoleTask> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saa_role_task
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SaaRoleTask record);
}