package com.Manager.userManager.saaUserPower.dao;

import com.Manager.userManager.saaUserPower.po.SaaUserPower;
import java.util.List;

public interface SaaUserPowerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saa_user_power
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saa_user_power
     *
     * @mbggenerated
     */
    int insert(SaaUserPower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saa_user_power
     *
     * @mbggenerated
     */
    SaaUserPower selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saa_user_power
     *
     * @mbggenerated
     */
    List<SaaUserPower> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table saa_user_power
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SaaUserPower record);
}